#ifndef __ATTRIB_H_
#define __ATTRIB_H_

typedef enum HtmlAttribKey HtmlAttribKey;
enum HtmlAttribKey {
	HTML_ATTRIB_NONE,
	
	HTML_ATTRIB_UNKNOWN,
	
	HTML_ATTRIB_ABBR,
	HTML_ATTRIB_ACCEPT_CHARSET,
	HTML_ATTRIB_ACCEPT,
	HTML_ATTRIB_ACCESSKEY,
	HTML_ATTRIB_ACTION,
	HTML_ATTRIB_ALIGN,
	HTML_ATTRIB_ALT,
	HTML_ATTRIB_AXIS,
	
	HTML_ATTRIB_BORDER,
	
	HTML_ATTRIB_CELLPADDING,
	HTML_ATTRIB_CELLSPACING,
	HTML_ATTRIB_CHAR,
	HTML_ATTRIB_CHAROFF,
	HTML_ATTRIB_CHARSET,
	HTML_ATTRIB_CHECKED,
	HTML_ATTRIB_CITE,
	HTML_ATTRIB_CLASS,
	HTML_ATTRIB_CODETYPE,
	HTML_ATTRIB_COLS,
	HTML_ATTRIB_COLSPAN,
	HTML_ATTRIB_CONTENT,
	HTML_ATTRIB_COORDS,
	
	HTML_ATTRIB_DATA,
	HTML_ATTRIB_DATETIME,
	HTML_ATTRIB_DECLARE,
	HTML_ATTRIB_DEFER,
	HTML_ATTRIB_DIR,
	HTML_ATTRIB_DISABLED,
	
	HTML_ATTRIB_ENCTYPE,
	
	HTML_ATTRIB_FACE,
	HTML_ATTRIB_FOR,
	HTML_ATTRIB_FRAME,
	HTML_ATTRIB_FRAMEBORDER,
	
	HTML_ATTRIB_HEADERS,
	HTML_ATTRIB_HEIGHT,
	HTML_ATTRIB_HREF,
	HTML_ATTRIB_HREFLANG,
	HTML_ATTRIB_HSPACE,
	HTML_ATTRIB_HTTP_EQUIV,
	
	HTML_ATTRIB_ID,
	HTML_ATTRIB_ISMAP,
	
	HTML_ATTRIB_LABEL,
	HTML_ATTRIB_LANG,
	HTML_ATTRIB_LONGDESC,
	
	HTML_ATTRIB_MARGINHEIGHT,
	HTML_ATTRIB_MARGINWIDTH,
	HTML_ATTRIB_MAXLENGTH,
	HTML_ATTRIB_MEDIA,
	HTML_ATTRIB_METHOD,
	HTML_ATTRIB_MULTIPLE,
	
	HTML_ATTRIB_NAME,
	HTML_ATTRIB_NOHREF,
	HTML_ATTRIB_NORESIZE,
	
	HTML_ATTRIB_ONBLUR,
	HTML_ATTRIB_ONCHANGE,
	HTML_ATTRIB_ONCLICK,
	HTML_ATTRIB_ONDBLCLICK,
	HTML_ATTRIB_ONFOCUS,
	HTML_ATTRIB_ONKEYDOWN,
	HTML_ATTRIB_ONKEYPRESS,
	HTML_ATTRIB_ONKEYUP,
	HTML_ATTRIB_ONLOAD,
	HTML_ATTRIB_ONMOUSEDOWN,
	HTML_ATTRIB_ONMOUSEMOVE,
	HTML_ATTRIB_ONMOUSEOUT,
	HTML_ATTRIB_ONMOUSEOVER,
	HTML_ATTRIB_ONMOUSEUP,
	HTML_ATTRIB_ONRESET,
	HTML_ATTRIB_ONSELECT,
	HTML_ATTRIB_ONSUBMIT,
	HTML_ATTRIB_ONUNLOAD,
	
	HTML_ATTRIB_PROFILE,
	
	HTML_ATTRIB_READONLY,
	HTML_ATTRIB_REL,
	HTML_ATTRIB_REV,
	HTML_ATTRIB_ROWS,
	HTML_ATTRIB_ROWSPAN,
	HTML_ATTRIB_RULES,
	
	HTML_ATTRIB_SCHEME,
	HTML_ATTRIB_SCOPE,
	HTML_ATTRIB_SCROLLING,
	HTML_ATTRIB_SELECTED,
	HTML_ATTRIB_SHAPE,
	HTML_ATTRIB_SIZE,
	HTML_ATTRIB_SPAN,
	HTML_ATTRIB_SRC,
	HTML_ATTRIB_STANDBY,
	HTML_ATTRIB_STYLE,
	HTML_ATTRIB_SUMMARY,
	
	HTML_ATTRIB_TABINDEX,
	HTML_ATTRIB_TARGET,
	HTML_ATTRIB_TITLE,
	HTML_ATTRIB_TYPE,
	
	HTML_ATTRIB_USEMAP,
	
	HTML_ATTRIB_VALIGN,
	HTML_ATTRIB_VALUE,
	HTML_ATTRIB_VALUETYPE,
	
	HTML_ATTRIB_WIDTH,
	
	HTML_ATTRIB_XML__LANG,
	HTML_ATTRIB_XMLNS,
	
	HTML_ATTRIB_KEYS,
};

typedef struct HtmlAttrib HtmlAttrib;
struct HtmlAttrib {
	HtmlAttribKey key;
	char *key_name;
	
	char *value;
	HtmlAttrib *next;
};

extern const char *html_attrib[HTML_ATTRIB_KEYS];

HtmlAttrib *attrib_append(HtmlAttrib **attrib, HtmlAttrib *item);

#endif
